print(len([None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, None, None, None, 
None, None, 'Sell', 'Sell', 'Sell', 
'Sell', 'Buy', 'Sell', 'Sell', 'Sell', 
'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 
'Buy', 'Buy', 'Sell', 'Buy', 'Buy', 'Sell', 
'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 
'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 
'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 
'Buy', 'Sell', 'Buy', 'Buy', 'Sell', 'Sell', 
'Sell', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 
'Sell', 'Sell', 'Sell', 'Buy', 'Buy', 'Buy', 
'Buy', 'Buy', 'Buy', 'Buy', 'Sell', 'Sell', 
'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 
'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Buy', 
'Sell', 'Sell', 'Buy', 'Buy', 'Buy', 'Buy', 
'Buy', 'Sell', 'Sell', 'Sell', 'Sell', 'Buy', 
'Buy', 'Buy', 'Buy', 'Sell', 'Buy', 'Buy', 
'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 
'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 
'Buy', 'Buy', 'Buy', 'Buy', 'Sell', 'Sell', 
'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 
'Sell', 'Buy', 'Buy', 'Buy', 'Sell', 'Buy', 
'Sell', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 
'Sell', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 
'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 
'Sell', 'Sell', 'Sell', 'Sell', 'Buy', 'Buy', 
'Sell', 'Buy', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 
'Sell', 'Sell', 'Buy', 'Buy', 'Sell', 'Sell', 'Sell', 
'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 
'Sell', 'Sell', 'Sell', 'Buy', 'Sell', 'Buy', 'Buy', 'Sell']))
